function generateMarkdown(data) {
	return `
## ${data.title}
## Description
${data.description}
## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Questions](#questions)
## Installation
${data.installation}
## Usage
${data.usage}
## Contributing
${data.contribution}
## Tests
${data.test}
## Questions
  
Find me on GitHub: [${data.github}](https://github.com/${data.github}).  
  
Email me with any questions: ${data.email}.  
This README was generated by [README-generator](https://github.com/Somdobomk/Module9-Challenge)`;
}

module.exports = generateMarkdown;
